// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(DBProyectoContext))]
    partial class DBProyectoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Actividad", b =>
                {
                    b.Property<int>("IdActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActividad"), 1L, 1);

                    b.Property<int>("CuposDisponible")
                        .HasColumnType("int");

                    b.Property<string>("DescActividad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HorarioDisponible")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdActividad")
                        .HasName("PK__Activida__5EAF86A4DD3D9F90");

                    b.ToTable("Actividad", (string)null);
                });

            modelBuilder.Entity("Entities.Bitacora", b =>
                {
                    b.Property<long>("ConsecutivoError")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ConsecutivoError"), 1L, 1);

                    b.Property<int>("CodigoError")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ConsecutivoError")
                        .HasName("PK_TBITACORA");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Bitacora", (string)null);
                });

            modelBuilder.Entity("Entities.Cabina", b =>
                {
                    b.Property<int>("IdCabina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCabina"), 1L, 1);

                    b.Property<int>("CamasDisponibles")
                        .HasColumnType("int");

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("int");

                    b.Property<string>("DescCabina")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<int>("PrecioNoche")
                        .HasColumnType("int");

                    b.HasKey("IdCabina")
                        .HasName("PK__Cabina__8BC666EC04EE6EDC");

                    b.ToTable("Cabina", (string)null);
                });

            modelBuilder.Entity("Entities.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NumTelefono")
                        .HasColumnType("int");

                    b.Property<int>("Usuario")
                        .HasColumnType("int");

                    b.HasKey("IdCliente")
                        .HasName("PK__Cliente__D5946642FDCABD1F");

                    b.HasIndex("Usuario");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("Entities.Inventario", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"), 1L, 1);

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("int");

                    b.Property<string>("DescProducto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdProducto")
                        .HasName("PK__Inventar__098892108EA7CE27");

                    b.ToTable("Inventario", (string)null);
                });

            modelBuilder.Entity("Entities.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"), 1L, 1);

                    b.Property<int>("Actividad")
                        .HasColumnType("int");

                    b.Property<int>("Cabina")
                        .HasColumnType("int");

                    b.Property<int>("CantDias")
                        .HasColumnType("int");

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("int");

                    b.Property<int>("Cliente")
                        .HasColumnType("int");

                    b.Property<int>("PrecioTotal")
                        .HasColumnType("int");

                    b.HasKey("IdReserva")
                        .HasName("PK__Reserva__0E49C69D4C99A6A6");

                    b.HasIndex("Actividad");

                    b.HasIndex("Cabina");

                    b.HasIndex("Cliente");

                    b.ToTable("Reserva", (string)null);
                });

            modelBuilder.Entity("Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"), 1L, 1);

                    b.Property<string>("DescRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdRol")
                        .HasName("PK__Rol__2A49584CC90E41EF");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__5B65BF9761DDADEF");

                    b.HasIndex("Rol");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Entities.Bitacora", b =>
                {
                    b.HasOne("Entities.Usuario", "IdUsuarioNavigation")
                        .WithMany("Bitacoras")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Bitacora_Usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Entities.Cliente", b =>
                {
                    b.HasOne("Entities.Usuario", "UsuarioNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("Usuario")
                        .IsRequired()
                        .HasConstraintName("FK__Cliente__Usuario__6EF57B66");

                    b.Navigation("UsuarioNavigation");
                });

            modelBuilder.Entity("Entities.Reserva", b =>
                {
                    b.HasOne("Entities.Actividad", "ActividadNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("Actividad")
                        .IsRequired()
                        .HasConstraintName("FK__Reserva__Activid__6FE99F9F");

                    b.HasOne("Entities.Cabina", "CabinaNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("Cabina")
                        .IsRequired()
                        .HasConstraintName("FK__Reserva__Cabina__70DDC3D8");

                    b.HasOne("Entities.Cliente", "ClienteNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("Cliente")
                        .IsRequired()
                        .HasConstraintName("FK__Reserva__Cliente__71D1E811");

                    b.Navigation("ActividadNavigation");

                    b.Navigation("CabinaNavigation");

                    b.Navigation("ClienteNavigation");
                });

            modelBuilder.Entity("Entities.Usuario", b =>
                {
                    b.HasOne("Entities.Rol", "RolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("Rol")
                        .IsRequired()
                        .HasConstraintName("FK__Usuario__Rol__72C60C4A");

                    b.Navigation("RolNavigation");
                });

            modelBuilder.Entity("Entities.Actividad", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Entities.Cabina", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Entities.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Entities.Usuario", b =>
                {
                    b.Navigation("Bitacoras");

                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
